version: "3.9"
services:
  tabular-data:
    container_name: tabular-data
    image: frankfeng78/tabula-data:0.1.41
    ports:
      - 9092:8501
    volumes:
      - ./tmp:/tmp
      - ./logs:/app/logs
    environment:
      - BASE_URL=http://nettoolkit:3000
      - LOGS_FOLDER=/app/logs
      - LOG_ARTICLE=TRUE
      - TEMP_FOLDER=/tmp
    env_file:
      - .env
    depends_on:
      - nettoolkit
 
  nettoolkit:
    container_name: nettoolkit
    image: frankfeng78/nettoolkit:0.1.7
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs
      - ./tmp:/tmp

networks:
  default:
    name: tabular
