
import pytest

from TabFuncFlow.utils.table_utils import single_html_table_to_markdown

html_content_29100749_table_2 = """
<div class="tables frame-topbot rowsep-0 colsep-0" id="t0015"><span class="captions text-s"><span id="ca0020"><p id="sp0030"><span class="label">Table 2</span>. Concentrations (ng/ml) of BP-1, BP-3 and 4-MBP in maternal serum, maternal urine, amniotic fluid and fetal serum from four different pregnant women: samples collected simultaneously at respectively cordocentesis and delivery.</p></span></span><div class="groups"><table><thead><tr class="valign-top"><td class="rowsep-0" rowspan="2" scope="col"><span class="screen-reader-only">Empty Cell</span></td><th class="rowsep-1" rowspan="2" scope="col">ID</th><th class="rowsep-1" colspan="4" scope="col">Cordocentesis</th><th class="rowsep-1" colspan="3" scope="col">Delivery</th></tr><tr class="rowsep-1 valign-top"><th scope="col">Urine</th><th scope="col">Amnion</th><th scope="col">Serum</th><th scope="col">Fetal serum</th><th scope="col">Urine</th><th scope="col">Serum</th><th scope="col">Cord blood</th></tr></thead><tbody><tr><th rowspan="4" scope="row">BP-1</th><td>1</td><td>–</td><td>&lt; LOD<a class="anchor anchor-primary" data-sd-ui-side-panel-opener="true" data-xocs-content-id="tf0025" data-xocs-content-type="reference" href="#tf0025" name="btf0025"><span class="anchor-text-container"><span class="anchor-text"><sup>a</sup></span></span></a></td><td>&lt; LOD</td><td>&lt; LOD</td><td>–</td><td>–</td><td>–</td></tr><tr><td>2</td><td>–</td><td>&lt; LOD</td><td>2.28</td><td>0.36</td><td>–</td><td>&lt; LOD</td><td>&lt; LOD</td></tr><tr><td>3</td><td>6.47</td><td>&lt; LOD</td><td>&lt; LOD</td><td>&lt; LOD</td><td>–</td><td>–</td><td>–</td></tr><tr><td>4</td><td>3.68</td><td>–</td><td>&lt; LOD</td><td>&lt; LOD</td><td>4.13</td><td>&lt; LOD</td><td>&lt; LOD</td></tr><tr><th rowspan="4" scope="row">BP-3</th><td>1</td><td>–</td><td>&lt; LOD</td><td>0.34</td><td>&lt; LOD</td><td>–</td><td>–</td><td>–</td></tr><tr><td>2</td><td>–</td><td>0.33</td><td>37</td><td>10.1</td><td>–</td><td>1</td><td>&lt; LOD</td></tr><tr><td>3</td><td>106.3</td><td>&lt; LOD</td><td>0.77</td><td>&lt; LOD</td><td>–</td><td>–</td><td>–</td></tr><tr><td>4</td><td>17.9</td><td>–</td><td>0.55</td><td>&lt; LOD</td><td>32</td><td>0.77</td><td>&lt; LOD</td></tr><tr><th rowspan="4" scope="row">4-MBP</th><td>1</td><td>–</td><td>&lt; LOD</td><td>0.59</td><td>0.31</td><td>–</td><td>–</td><td>–</td></tr><tr><td>2</td><td>–</td><td>&lt; LOD</td><td>1.62</td><td>&lt; LOD</td><td>–</td><td>1.12</td><td>&lt; LOD</td></tr><tr><td>3</td><td>&lt; LOD</td><td>&lt; LOD</td><td>1.04</td><td>1.3</td><td>–</td><td>–</td><td>–</td></tr><tr><td>4</td><td>0.61</td><td>–</td><td>4.98</td><td>1.19</td><td>&lt; LOD</td><td>6.31</td><td>&lt; LOD</td></tr></tbody></table></div><div class="legend"><div class="u-margin-s-bottom" id="sp0035">BP-1: benzophenone-1; BP-3: benzophenone-3; 4-MBP: 4-methyl-benzophenone.</div></div><dl class="footnotes"><dt id="tf0025">a</dt><dd><div class="u-margin-s-bottom" id="np0025">LOD: limit of detection.</div></dd></dl></div>
"""

def test_html_to_markdown():
    md_table = single_html_table_to_markdown(html_content_29100749_table_2)
    assert md_table is not None
    assert len(md_table) > 0
    