title = "Plasma Concentrations of Carbohydrates and Sugar Alcohols in Term Newborns after Milk Feeding"

full_text = """
Abstract
Nonglucose carbohydrates such as galactose, mannose, and inositol play a clinically important role in fetal and neonatal nutrition, though little is known about their metabolism in the neonate. The aim of this study was to determine whether postprandial changes in plasma carbohydrate and sugar alcohol concentrations are affected by clinical variables such as postnatal age (PNA), milk type, feeding volume, or feeding duration in term newborns. Neonates ( n = 26) taking intermittent enteral feedings were enrolled. Blood samples were obtained at baseline (immediately before the start of a feeding) and at 2–3 subsequent time points up to 110 min. Postprandial rise was only observed for plasma glucose concentrations [Glu] and plasma galactose concentrations [Gal] and clinical variables did not predict this change. Despite equimolar delivery in milk, the median of [Glu] rise minus [Gal] rise from baseline to second postprandial plasma sample was 674 μ M (−38, 3333 μ M; p < 0.0001), reflecting efficient hepatic first-pass metabolism of galactose. A significant PNA effect on [Gal] was observed such that for each day PNA there was an 18% decrease in [Gal] ( p = 0.03). [Gal] are a function of PNA, suggesting maintenance of a significant ductus venosus shunt in term infants.
Subjects
This study was approved by the Institutional Review Board at the University of Parma, Parma, Italy, and at the University of Colorado Denver, Denver, CO. Informed consent was obtained from parent or guardian of the infants before the study by Clinical Research Center nurses or study investigators. Subjects were recruited from either the level I nursery or from the NICU. Infants were considered eligible for the study if they were greater than 36 wk gestation and taking full, intermittent enteral feedings of formula or breast milk by mouth. Those infants who were initially admitted to the NICU were considered for enrollment only after any acute medical problems had resolved and the infant was at the point of receiving well baby care. For each infant studied, the following information was collected: GA, PNA, birth weight, infant weight at the time of the study, milk type, intake volume per kilogram body weight, and duration of feeding. For breast fed infants, intake volume was determined by weighing the infant before and after the feeding. Attempts were made to select infants that were taking on average 10 mL/kg/feed over a 20–30 min time period to ensure adequate absorption of nutrients in milk from the intestine. Blood samples were obtained either by heel stick or by venous collection at baseline (immediately before the start of a feeding) and at 2–3 subsequent time points. A misinterpretation of study protocol resulted in a minor difference in sample collection between centers. Samples were correctly obtained from Denver infants at 30, 60, and 90 min from baseline (start of the feeding) and from Parma infants at 30 and 60 min postfeed completion (range of 40–110 min postbaseline). One Parma infant also had a sample taken at 90 min postfeed completion (115 min postbaseline). The samples were centrifuged immediately and the plasma stored at −70 to −80°C until the time of analysis.
Plasma carbohydrate analysis
Plasma was analyzed for glucose, galactose, mannose, fucose, inositol, glycerol, mannitol, erythritol, sorbitol, ribitol, glucosamine, and galactosamine as previously described ( 2 ). All plasma samples were analyzed at the University of Colorado. Briefly, the plasma was thawed quickly; 0.1 mL of 0.3 N zinc sulfate containing 30 mg% xylitol as an internal standard was added to 0.1 mL plasma, mixed well and another 0.1 mL of 0.3 N barium hydroxide was added. The mixture was centrifuged at 14,000 g for 10 min and the supernatant was filtered through a 0.45 μ m filter before loading on a refrigerated autosampler for HPLC analysis. A Dionex HPLC analyzer equipped with a CarboPac MA1 anion-exchange column was used for the separation of the hexoses and sugar alcohols (Dionex, Sunnyvale, CA). The analysis was run isocratically with 500 mM sodium hydroxide for 25 min, followed by a step change to 400 mM sodium hydroxide (prepared with degassed, deionized water) for 20 min at ambient temperature. The flow rate was 0.4 mL per hour. A CarboPac PA 10 column was used to analyze galactose, galactosamine, and glucosamine. The system was run isocratically with 18 mM sodium hydroxide at ambient temperature. The flow rate was 0.6 mL per hour. All the peaks were quantified by using a pulse amperometric detector (Dionex ED40 Electrochemical Detector) with a gold electrode. The Dionex PeakNet software was used for instrument operation and data analysis. All concentrations are expressed as micromolar.
Statistical analysis
Results are presented as median (range) unless otherwise specified. All analyses assumed a two-sided test of hypothesis with an overall significance level of 0.05. Because of small sample sizes, nonparametric tests were used to compare baseline characteristics across centers. In addition, Fisher’s exact test was used to analyze milk type across centers. Plasma galactose concentration [Gal] rise minus plasma glucose concentration [Glu] rise to second postprandial blood sample was tested using a Wilcoxon signed-rank test because of nonnormality. Longitudinal plasma carbohydrate and sugar alcohol concentrations were modeled using the mixed procedure in SAS (SAS Institute, Inc., Cary NC). A random intercept was included in all models and a random slope was considered based on a likelihood ratio test. Under the full model, a likelihood ratio test was used to determine the covariance structure (unstructured or variance components). A log e transformation was used to normalize [Gal]. In all analyses, milk type (breast milk, formula or both) was considered a categorical variable.
RESULTS
Twenty-six infants were evaluated ( n = 9 from Denver and n = 17 from Parma) and all available clinical information is presented in Table 1 . The median PNA for the entire population of infants was 6 d (2–16 d) and the gestational age was 38 wk (36–41.5 wk). The median volume of milk taken at each feeding (breast, formula or both) was 16 mL · kg −1 (7–34 mL · kg −1 ) and the duration of feeding was 20 min (10–50 min), which indicates that these infants were taking adequate volumes of milk over a relatively brief time period. There were no significant differences in clinical characteristics between centers, with the exception that Denver infants were studied at a significantly younger PNA (median 2 d) than Parma infants (median 7 d, p = 0.0008).
Figure 1 illustrates the change in [Glu] and [Gal] for each patient from baseline to the second postprandial sample, or 60–110 min after the start of the milk feeding. Despite delivery in equimolar amounts from the breakdown of lactose in milk, the median of [Glu] rise minus [Gal] rise from baseline to the second postprandial plasma sample was 674 μ M (−38, 3333 μ M; p < 0.0001). This observation reflects a postprandial rise in [Glu] that was 60-fold higher than [Gal]. Clinical variables such as volume of milk ingested, gestational age, PNA, duration of feeding or milk type, or site of recruitment did not predict the change from baseline to peak concentration for either glucose or galactose.
A mixed model of [Gal] as a function of log e (minutes + 1) and age revealed a significant age effect such that for each day PNA there was an 18% decrease in [Gal], holding time constant ( p = 0.03). To further analyze the maturational age effect, infants were split into two groups, = 2 d PNA and >2 d PNA for exploratory analysis of [Gal] and [Glu] modeled separately as a function of age group and an interaction of log e (minutes +1) and age group through 90 min postbaseline ( Table 2 ). [Gal] was significantly higher at all time points in the younger infants. [Glu] was also significantly higher at baseline and estimated 30 min time point, but to a lesser degree than the [Gal] differences observed. The graphs in Figure 2 display the estimated mean [Gal] with both individual term infant [Gal] and shaded 95% confidence intervals, as well as a graphical description of the PNA effect on [Gal].
The concentrations of several other sugar alcohols and carbohydrates were measured at all time points, and baseline concentrations were as follows: glycerol (149.5, 40.1–357.2 μ M), inositol (141.3, 57.4–334.9 μ M), mannose (50.3, 4.0–110.9 μ M), mannitol (9.9, 1.1–32.5 μ M), and erythritol (7.5, 1.2–28.5 μ M). Sorbitol, ribitol, fucose, glucosamine, and galactosamine were detectable in the plasma but the concentrations were below the limits of accuracy for the HPLC methodology used (less than 5 μ M). None of these hexoses and sugar alcohols showed evidence of a postprandial increase in plasma concentration. Given the lack of postprandial rise, the association between clinical variables related to the feeding and sugar alcohol concentrations could not be examined.
DISCUSSION
The present study provides normative data for the plasma concentrations of several different carbohydrates after milk feeding in a reasonable number of newborn infants. These novel results should facilitate the interpretation of feeding studies for infants with disorders of carbohydrate metabolism such as IDMs or infants with IUGR. The results also provide novel evidence of a striking difference in [Gal] between relatively younger and older neonates. Such unique developmental patterns of changes in neonatal [Gal] indicate that marked changes in hepatic blood flow and/or functional capacity might affect hepatically cleared substrates in the immediate postnatal period.
Our study demonstrates a major difference in the hepatic uptake of galactose compared with glucose. Glucose and galactose are hydrolyzed in the intestine from lactose, the principle sugar in almost all mammalian milk. Previous studies in catheterized neonatal lambs have shown that after intestinal absorption, glucose and galactose are delivered to the liver via the portal vein in equimolar amounts ( 21 , 22 ). In this animal model, [Gal] increased significantly in the portal vein without any change in hepatic venous or femoral arterial circulation after nursing, demonstrating efficient hepatic galactose extraction in the first week of life. [Glu] increased in both hepatic and systemic circulations with no net hepatic glucose uptake. Furthermore, hepatic glucose release was observed in the fasted state ( 22 ). [Gal] measured in our study rose to only 1–2% of the [Glu] by the second postprandial plasma sample, which is consistent with previous work that galactose is almost cleared completely by the neonatal liver. We and others hypothesize that galactose derived from lactose in milk is used for the hepatic formation of glycogen and subsequent hepatic glucose release into the circulation during times of fasting ( 7 , 22 ).
Sparks et al. in 1982 and Siegel et al. in 1988 were the first to report postprandial [Gal] in term infants ( 11 , 23 ). In both studies, [Gal] increased significantly after a milk feeding and were within the range of 45 and 235 μ M. The present study was in significant agreement with those studies. [Gal] were all less than 230 μ M, though the majority of patients had [Gal] less than 55 μ M. The present study is the first, however, to show a maturational effect on [Gal], i.e. , [Gal] were higher in those infants fed in the first few days of life. Sparks et al. reported no effect of PNA on [Gal], though comparisons were made between relatively older neonates of 2, 2–5, and 5 wk of age compared with our studies in newborn infants who were all ≤16 d of age. One mechanism that would account for this observation is a patent DV, which shunts blood from the left portal vein directly to the confluence of the hepatic veins and inferior vena cava. Studies using serial postnatal liver ultrasounds have documented that the DV may remain patent for several days after birth in term infants and for longer periods of time in preterm infants ( 17 , 24 ). Loberant et al. ( 18 ) found that flow velocities through a patent DV were in the range of 0.15–0.70 m/s and decreased significantly in subsequent examinations over the first 2 wk of life. Newborn lambs in the first week of life can shunt as much as 25% of blood away from the portal circulation to the systemic circulation through the DV ( 25 , 26 ), further indicating its hemodynamic significance. Studies before ours have demonstrated a relationship between [Gal] and a patent DV in newborns. A persistent patent DV has been implicated in transient hypergalactosemia detected by neonatal mass screening for inborn errors of metabolism ( 20 ). Murayama et al. ( 19 ) found that the magnitude of blood flow through a patent DV correlated positively with [Gal] in 3 d old infants. Our study compared infants at several different PNAs over the first 2 wk of life and found that for each postnatal day, [Gal] fell by 18%. Given the above studies that demonstrate a hemodynamically significant post-natal DV and a correlation between DV patency and galactose measurements, the findings in our study may reflect a limitation of hepatic galactose clearance because of a persistent or slowly closing DV shunt.
It also is possible that the PNA effect on [Gal] found in the present study could reflect a relative immaturity of the liver to extract galactose in the first several days of life. This option appears less likely, given that our population of infants ranged from 36 to 41 wk gestation and gestational age was nonsignificant in our longitudinal [Gal] model. Furthermore, a patent DV during the immediate 4 or 5 postnatal days has already been shown by others ( 17 – 19 ). This finding of a DV shunt bypassing the portal vein mandates that systemic [Gal] concentrations must rise during those postnatal days. However, further maturation of hepatic enzymatic function also may occur postnatally once the neonate begins enteral feedings regardless of gestational age. Therefore, further studies are needed to establish the relationship between DV patency and [Gal] concentrations.
In the present study, we recruited patients from two different birth centers. Since there were some minor procedural differences between sites of enrollment such as timing and method of blood draw, we analyzed whether our results differed because of site of patient enrollment. [Gal] differed between centers but only as it reflected differences in PNA. Most of the 2 d old patients were enrolled in Denver and most of the patients greater than 2 d of age were enrolled in Parma, primarily because of differences in length of hospitalization for normal newborns in the different countries. As discussed above, this difference is most likely because of the PNA effect on [Gal] though we cannot completely exclude the effect of other unrecognized variables.
We measured the change in neonatal plasma concentrations of several other carbohydrates and sugar alcohols after a milk feeding. Cavalli et al. ( 8 ) measured free sugar and sugar alcohol concentrations in human breast milk and found that they are present but 100-fold lower than for lactose. Although several sugar alcohols, including inositol, glycerol, mannitol, and erythritol, are present in the plasma of term infants, we did not observe a postprandial increase in their plasma concentrations, probably because their concentrations in milk are relatively low, particularly compared with lactose. The concentration of oligosaccharides in human milk also is low compared with lactose; oligosaccharides account for 1% (wt/vol) of human milk versus lactose which accounts for 7% of human milk ( 27 ). Carbohydrates that compose the core of oligosaccharides, such as fucose and mannose, did not have a measurable postprandial rise, presumably reflecting their relatively low concentrations in milk. Furthermore, a growing body of evidence suggests that oligosaccharides are not hydrolyzed and absorbed from the small intestine, but instead contribute to the establishment of nonpathogenic colonic flora and inhibit binding of pathogens to the intestinal epithelial cell ( 28 , 29 ). For both of these reasons, a postprandial rise in concentration of fucose and mannose would not be expected.
In summary, this study found that glucose and galactose increase postprandially and that several other carbohydrates contained in milk do not. Further investigations are needed to define the individual roles of these carbohydrates and sugar alcohols in neonatal metabolism, whether the newborn infant produces these carbohydrates from glucose in adequate amounts to meet biologic requirements, or whether they are required nutritionally for optimal postnatal growth. Furthermore, our study continues to address the unique patterns of galactose metabolism in the neonatal diet. We demonstrate differences in [Glu] and [Gal] consistent with previous work that galactose is almost cleared completely by the neonatal liver and provide novel evidence of a marked difference in [Gal] between relatively younger and older neonates. In addition, to the extent that [Gal] may be a sensitive marker for hepatic blood flow and/or injury from prenatal DV dilatation and shunt in pathologic conditions such as IUGR, it is of great interest to carry out similar studies in infants in whom hepatic perfusion may be compromised.
Tables
Table 1 Patient clinical data by site
| Unnamed: 0 | Denver (n = 9) | Parma (n = 15)* | p † |
| --- | --- | --- | --- |
| Gestational age (wks) | 38 (37, 41.5) | 38 (36, 41)‡ | 0.25 |
| Birthweight (kg) | 2.8 (2.3, 3.5) | 3.1 (2.5, 4.5)‡ | 0.40 |
| Study weight (kg) | 2.8 (2.4, 3.5) | 3.2 (2.5, 4.3) | 0.14 |
| Intake volume (mL/kg) | 16.2 (10.9, 26.3) | 19.2 (6.9, 34.2) | 0.38 |
| Feed time (min) | 25 (14, 34) | 18 (10, 50) | 0.13 |
| Postnatal age (d) | 2 (2, 6) | 7 (2, 16) | 0.0008 |
| Milk type |  |  | 0.39§ |
| Breast milk (BM) | 1 (11%) | 5 (33.3%) |  |
| Formula (F) | 3 (33%) | 2 (13.3%) |  |
| BM + F | 5 (56%) | 8 (53.3%) |  |

Table 2 =2 d vs >2 d group analysis
| Group | Baseline | 30 min | 60 min | 90 min |
| --- | --- | --- | --- | --- |
| Galactose (μM) =2 d | 5.41 (1.95, 15.03) | 30.11 (12.05, 75.20) | 42.23 (16.68, 106.94) | 51.58 (20.10, 132.38) |
| Galactose (μM) >2 d | 1.03 (0.49, 2.17) | 4.37 (2.22, 8.63) | 5.82 (2.91, 11.64) | 6.88 (3.40, 13.95) |
| p | 0.01 | 0.001 | 0.001 | 0.001 |
| Glucose (μM) =2 d | 4604 (3874, 5335) | 4959 (4413, 5504) | 5028 (4454, 5603) | 5070 (4468, 5671) |
| Glucose (μM) >2 d | 3326 (2793, 3859) | 4252 (3850, 4654) | 4435 (4008, 4861) | 4543 (4094, 4991) |
| p | 0.007 | 0.04 | 0.1 | 0.16 |
"""